name: Impress Base Image Creation

on:
        push:
                branches: [main]
        schedule:
                - cron: '0 0 * * 0'
        workflow_dispatch:

jobs:
        deploy:
                runs-on: ubuntu-latest
                steps:
                        - uses: actions/checkout@v4.1.7

                        - name: Set up QEMU
                          uses: docker/setup-qemu-action@v3.2.0

                        - name: Set up Docker BuildX
                          uses: docker/setup-buildx-action@v3.6.1

                        - name: Login to Docker Hub
                          uses: docker/login-action@v3.3.0
                          with:
                                  username: ninjaninja140
                                  password: dckr_pat_hRtKqvYjkSHUP07u55yjwWTsny8

                        - name: Build and push
                          uses: docker/build-push-action@v6.7.0
                          with:
                                  push: true
                                  tags: ninjaninja140/impress-base:latest
